# Generated by Django 6.0.2 on 2026-02-11 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('level', models.CharField(choices=[('faculty', 'Факультетский'), ('course', 'Курсовой'), ('university', 'Университетский/межфакультетский'), ('interuniversity', 'Межуниверситетский/региональный'), ('all_russian', 'Всероссийский/межрегиональный'), ('chemistry_day', 'День химика'), ('cabbage', 'Капустник'), ('dedication', 'Посвящение в химики')], max_length=30, verbose_name='Уровень')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_first_time', models.BooleanField(default=False, verbose_name='Организовано впервые?')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('group', models.CharField(blank=True, default='', max_length=50, verbose_name='Группа (курс)')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=200, verbose_name='Роль')),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Часы')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.event', verbose_name='Мероприятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участия',
                'unique_together': {('student', 'event')},
            },
        ),
    ]
