# Generated by Django 6.0.2 on 2026-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('course', 'Курсовой'), ('faculty', 'Факультетский'), ('interfaculty', 'Межфакультетский'), ('university', 'Университетский'), ('interuniversity', 'Межуниверситетский'), ('regional', 'Региональный'), ('interregional', 'Межрегиональный'), ('all_russian', 'Всероссийский'), ('international', 'Международный'), ('chemistry_day', 'День химика'), ('cabbage', 'Капустник'), ('dedication', 'Посвящение в химики')], max_length=30, verbose_name='Уровень'),
        ),
    ]
