"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import json
import time
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Доверенные источники для CSRF (ваш домен Railway)
CSRF_TRUSTED_ORIGINS = [
    'https://web-production-a3ef4.up.railway.app',  # ваш точный URL
]

# Если вы планируете использовать несколько окружений, можно добавить шаблон:
# CSRF_TRUSTED_ORIGINS = ['https://*.up.railway.app']

# Обязательно для HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(&on8qru89lay&@icp4*!k+!2zo(8w+dxz*hn#_72mq1!)^w^l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.up.railway.app']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

#region agent log
def _agent_debug_log(hypothesis_id: str, message: str, data: dict) -> None:
    """
    Lightweight debug logger for automated analysis. Writes NDJSON lines.
    """
    try:
        log_path = BASE_DIR / "debug-7459a2.log"
        payload = {
            "sessionId": "7459a2",
            "runId": "pre-fix",
            "hypothesisId": hypothesis_id,
            "location": "config/settings.py:STATIC_CONFIG",
            "message": message,
            "data": data,
            "timestamp": int(time.time() * 1000),
        }
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(payload, ensure_ascii=False) + "\n")
    except Exception:
        # Instrumentation failures must never break the app
        pass

_agent_debug_log(
    "H1",
    "STATIC settings at import",
    {
        "DEBUG": DEBUG,
        "STATIC_URL": STATIC_URL,
        "STATIC_ROOT": str(STATIC_ROOT),
        "static_root_exists": os.path.isdir(STATIC_ROOT),
        "static_root_listing_sample": (
            os.listdir(STATIC_ROOT)[:10] if os.path.isdir(STATIC_ROOT) else []
        ),
    },
)

#region agent log
# Test H5: CompressedManifestStaticFilesStorage manifest.json existence
manifest_path = os.path.join(STATIC_ROOT, 'staticfiles.json')
_agent_debug_log(
    "H5",
    "Manifest file check for CompressedManifestStaticFilesStorage",
    {
        "manifest_path": manifest_path,
        "manifest_exists": os.path.isfile(manifest_path),
        "storage_class": STATICFILES_STORAGE,
    },
)

# Test H6: Check if admin CSS file exists in STATIC_ROOT
admin_css_path = os.path.join(STATIC_ROOT, 'admin', 'css', 'base.css')
_agent_debug_log(
    "H6",
    "Admin CSS file existence check",
    {
        "admin_css_path": admin_css_path,
        "admin_css_exists": os.path.isfile(admin_css_path),
        "admin_dir_exists": os.path.isdir(os.path.join(STATIC_ROOT, 'admin')),
    },
)

# Test H7: WhiteNoise configuration check
try:
    import whitenoise
    whitenoise_version = getattr(whitenoise, "__version__", None)
    _agent_debug_log(
        "H7",
        "WhiteNoise import and version check",
        {
            "whitenoise_imported": True,
            "whitenoise_has_version_attr": hasattr(whitenoise, "__version__"),
            "whitenoise_version": whitenoise_version,
        },
    )
except Exception as e:
    _agent_debug_log(
        "H7",
        "WhiteNoise import and version check",
        {
            "whitenoise_imported": False,
            "error_type": type(e).__name__,
            "error": str(e),
        },
    )
#endregion agent log

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'achievements',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # обязательно после SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True