-- Migrate existing achievement-tracking data from the previous SQLite database.
INSERT INTO students (id, full_name, "group") VALUES (1, 'Ушаков Егор Андреевич', '5');
INSERT INTO students (id, full_name, "group") VALUES (2, 'Сукманов Матвей Дмитриевич', '5');
INSERT INTO students (id, full_name, "group") VALUES (3, 'Белый Илья Михайлович', '3');
INSERT INTO students (id, full_name, "group") VALUES (4, 'Коблов Михаил Андреевич', '2');
INSERT INTO students (id, full_name, "group") VALUES (5, 'Гоголев Аким Дмитриевич', '2');
INSERT INTO students (id, full_name, "group") VALUES (6, 'Калинкин Дмитрий Викторович', '3');
INSERT INTO students (id, full_name, "group") VALUES (7, 'Тулеев Михаил Олегович', '5');
INSERT INTO students (id, full_name, "group") VALUES (8, 'Радышевская Анна Андреевна', '1');
INSERT INTO students (id, full_name, "group") VALUES (9, 'Родионова Наталья Михайловна', '4');
INSERT INTO students (id, full_name, "group") VALUES (10, 'Осипова Анастасия Александровна', '2');
INSERT INTO students (id, full_name, "group") VALUES (11, 'Кузнецов Александр Ильич', '5');
INSERT INTO students (id, full_name, "group") VALUES (12, 'Люхтер Софья Александровна', '3');
INSERT INTO students (id, full_name, "group") VALUES (13, 'Тарасов Владимир Петрович', '2');
INSERT INTO students (id, full_name, "group") VALUES (14, 'Уткин Роман Антонович', '3');
INSERT INTO students (id, full_name, "group") VALUES (15, 'Сергеева Полина Андреевна', '3');
INSERT INTO students (id, full_name, "group") VALUES (16, 'Гришина Вероника Павловна', '2');
INSERT INTO students (id, full_name, "group") VALUES (17, 'Осинцев Тимофей Александрович', '5');
INSERT INTO students (id, full_name, "group") VALUES (18, 'Яшина Ксения Николаевна', '2');
INSERT INTO students (id, full_name, "group") VALUES (19, 'Брызгалов Михаил Евгеньевич', '3');
INSERT INTO students (id, full_name, "group") VALUES (20, 'Бушуева Алина Никитична', '2');
INSERT INTO students (id, full_name, "group") VALUES (21, 'Велиев Руслан Теймурович', '2');
INSERT INTO students (id, full_name, "group") VALUES (22, 'Гончаров Артём Юрьевич', '5');
INSERT INTO students (id, full_name, "group") VALUES (23, 'Матанова Алиса Васильевна', '2');
INSERT INTO students (id, full_name, "group") VALUES (24, 'Метленков Никита Алексеевич', '3');
INSERT INTO students (id, full_name, "group") VALUES (25, 'Мишина Анастасия Юрьевна', '2');
INSERT INTO students (id, full_name, "group") VALUES (26, 'Палий Екатерина Константиновна', '2');
INSERT INTO students (id, full_name, "group") VALUES (27, 'Пальцев Олег Сергеевич', '4');
INSERT INTO students (id, full_name, "group") VALUES (28, 'Перфильева Дарья Андреевна', '2');
INSERT INTO students (id, full_name, "group") VALUES (29, 'Самофалов Павел Сергеевич', '4');
INSERT INTO students (id, full_name, "group") VALUES (30, 'Савина Виктория Владимировна', '3');
INSERT INTO students (id, full_name, "group") VALUES (31, 'Синицын Арсений Александрович', '1');
INSERT INTO students (id, full_name, "group") VALUES (32, 'Соловьева София Николаевна', '2');
INSERT INTO students (id, full_name, "group") VALUES (33, 'Стамблер Дмитрий Александрович', '5');
INSERT INTO students (id, full_name, "group") VALUES (34, 'Стефаниди Ксения Романовна', '3');
INSERT INTO students (id, full_name, "group") VALUES (35, 'Троицкая Ольга Сергеевна', '3');
INSERT INTO students (id, full_name, "group") VALUES (36, 'Фокина Анна Сергеевна', '4');
INSERT INTO students (id, full_name, "group") VALUES (37, 'Хащеватская Валерия Ильинична', '3');
INSERT INTO students (id, full_name, "group") VALUES (38, 'Шумеева Виолетта Игоревна', '2');
INSERT INTO students (id, full_name, "group") VALUES (39, 'Цветков Владимир Дмитриевич', '4');
INSERT INTO students (id, full_name, "group") VALUES (40, 'Рындевич Алина Александровна', '2');
INSERT INTO students (id, full_name, "group") VALUES (41, 'Мирошниченко Кирилл Дмитриевич', '5');
INSERT INTO students (id, full_name, "group") VALUES (42, 'Рангульт Дмитрий Романович', '1');
INSERT INTO students (id, full_name, "group") VALUES (43, 'Ляпина Елизавета Алексеевна', '3');
INSERT INTO students (id, full_name, "group") VALUES (44, 'Осинцев Тимофей  Александрович', '5');
INSERT INTO students (id, full_name, "group") VALUES (45, 'Солнцева Алина Викторовна', '3');
INSERT INTO students (id, full_name, "group") VALUES (46, 'Титова Валерия Александровна', '3');
INSERT INTO students (id, full_name, "group") VALUES (47, 'Таиров Самир Аделевич', '4');
INSERT INTO students (id, full_name, "group") VALUES (48, 'Нехворощ Вадим Павлович', '1');
INSERT INTO students (id, full_name, "group") VALUES (49, 'Вышинский Никита Андреевич', '1');
INSERT INTO students (id, full_name, "group") VALUES (50, 'Поздняков Дмитрий Евгеньевич', '1');
INSERT INTO students (id, full_name, "group") VALUES (51, 'Вдовченко Никита Александрович', '6');
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (1, 'Турнир по армрестлингу', 'faculty', '2025-11-21', '2025-11-21', true);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (2, 'Турнир по волейболу', 'faculty', '2025-11-29', '2025-11-29', true);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (3, 'х34', 'course', '2025-10-05', '2025-10-05', false);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (4, 'Расширенное заседание Ученого совета Химического факультета, посвященное 90-летию со дня рождения академика Н.С. Зефирова', 'faculty', '2025-09-11', '2025-09-11', false);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (5, 'Своя Игра', 'faculty', '2025-11-29', '2025-11-29', true);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (6, 'Школа актива', 'faculty', '2025-11-07', '2025-11-09', true);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (7, 'Конкурс групп', 'course', '2025-09-01', '2025-12-01', true);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (8, 'Школа профоргов 1 курса', 'course', '2025-09-24', '2025-10-08', false);
INSERT INTO events (id, name, level, start_date, end_date, is_first_time) VALUES (9, 'Медиашкола pixel-техники', 'course', '2025-09-01', '2025-12-01', true);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (1, 1, 1, 'руководитель (главный организатор)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (2, 2, 1, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (3, 3, 1, 'организатор (отв. за отдельный блок)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (4, 4, 1, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (5, 5, 1, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (6, 6, 1, 'волонтер тех. части (фотограф, дизайнер, обеспечение безопасности, повар, техник, информационная работа и т.п.)', 4);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (7, 1, 2, 'руководитель (главный организатор)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (8, 2, 2, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (9, 7, 2, 'организатор (отв. за отдельный блок)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (10, 4, 2, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (11, 5, 2, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (12, 8, 2, 'волонтер тех. части (фотограф, дизайнер, обеспечение безопасности, повар, техник, информационная работа и т.п.)', 8);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (13, 1, 3, 'руководитель (главный организатор)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (14, 2, 3, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (15, 9, 3, 'организатор (отв. за отдельный блок)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (16, 10, 3, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (17, 11, 3, 'организатор (отв. за отдельный блок)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (18, 12, 3, 'организатор (отв. за отдельный блок)', 30);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (19, 13, 3, 'организатор (отв. за отдельный блок)', 30);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (20, 14, 3, 'организатор (отв. за отдельный блок)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (21, 15, 3, 'организатор (отв. за отдельный блок)', 30);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (22, 5, 3, 'организатор (отв. за отдельный блок)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (23, 16, 3, 'организатор (отв. за отдельный блок)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (24, 17, 3, 'волонтер тех. части (фотограф, дизайнер, обеспечение безопасности, повар, техник, информационная работа и т.п.)', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (25, 18, 3, 'волонтер тех. части (фотограф, дизайнер, обеспечение безопасности, повар, техник, информационная работа и т.п.)', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (26, 19, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (27, 20, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (28, 21, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (29, 22, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (30, 23, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (31, 24, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (32, 25, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (33, 26, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (34, 27, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (35, 28, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (36, 29, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (37, 30, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (38, 31, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (39, 32, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (40, 33, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (41, 34, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (42, 35, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (43, 36, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (44, 37, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (45, 38, 3, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (46, 39, 4, 'волонтер', 2);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (47, 17, 4, 'волонтер', 2);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (48, 15, 5, 'руководитель (главный организатор)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (49, 2, 5, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (50, 40, 5, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (51, 41, 5, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (52, 42, 5, 'волонтер', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (53, 12, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (54, 43, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (55, 44, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (56, 9, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (57, 40, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (58, 34, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (59, 2, 6, 'руководитель (главный организатор)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (60, 14, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (61, 1, 6, 'организатор (отв. за отдельный блок)', 40);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (62, 11, 6, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (63, 10, 7, 'организатор (отв. за отдельный блок)', 15);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (64, 9, 7, 'организатор (отв. за отдельный блок)', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (65, 27, 7, 'волонтер', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (66, 17, 8, 'руководитель (главный организатор)', 15);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (67, 45, 8, 'организатор (отв. за отдельный блок)', 15);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (68, 40, 8, 'помощник организатора', 5);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (69, 46, 8, 'лектор', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (70, 47, 8, 'лектор', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (71, 29, 8, 'лектор', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (72, 15, 8, 'лектор', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (73, 9, 8, 'фотограф', 10);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (74, 48, 8, 'волонтер', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (75, 49, 8, 'волонтер', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (76, 50, 8, 'волонтер', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (77, 43, 8, 'волонтер', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (78, 14, 8, 'волонтер', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (79, 1, 8, 'волонтер', 1);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (80, 11, 9, 'руководитель (главный организатор)', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (81, 51, 9, 'помощник организатора', 20);
INSERT INTO participations (id, student_id, event_id, role, hours) VALUES (82, 49, 9, 'волонтер тех. части (фотограф, дизайнер, обеспечение безопасности, повар, техник, информационная работа и т.п.)', 4);

-- Keep the serial sequences in sync with the explicit ids inserted above.
SELECT setval(pg_get_serial_sequence('students', 'id'), COALESCE((SELECT MAX(id) FROM students), 1));
SELECT setval(pg_get_serial_sequence('events', 'id'), COALESCE((SELECT MAX(id) FROM events), 1));
SELECT setval(pg_get_serial_sequence('participations', 'id'), COALESCE((SELECT MAX(id) FROM participations), 1));
